# Generated by Django 6.0.8 on 2026-08-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(db_index=True, max_length=50)),
                ('source_study', models.CharField(max_length=100)),
                ('all_samples_same_case', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=50)),
                ('qc_pass', models.BooleanField()),
                ('exclusion_reason', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=50)),
                ('was_in_previous_release', models.BooleanField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level_1', models.CharField(blank=True, max_length=100, null=True)),
                ('country_latitude', models.FloatField(blank=True, null=True)),
                ('country_longitude', models.FloatField(blank=True, null=True)),
                ('admin_level_1_latitude', models.FloatField(blank=True, null=True)),
                ('admin_level_1_longitude', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ena', models.CharField(blank=True, max_length=50, null=True)),
                ('pct_callable', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_records', to='datasets.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['country'], name='explorer_sa_country_23a9d0_idx'), models.Index(fields=['year'], name='explorer_sa_year_14025c_idx'), models.Index(fields=['qc_pass'], name='explorer_sa_qc_pass_9bbaa9_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'sample'), name='unique_sample_per_dataset')],
            },
        ),
    ]
