# Generated by Django 6.0.8 on 2026-08-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplerecord',
            old_name='source_study',
            new_name='study',
        ),
    ]
