# Generated by Django 6.0.8 on 2026-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_rename_source_study_samplerecord_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerecord',
            name='source_order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
