# Generated by Django 6.0.8 on 2026-09-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_samplerecord_source_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerecord',
            name='all_samples_same_case',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='samplerecord',
            name='ena',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
