# Generated by Django 6.0.8 on 2026-09-04 15:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
                ('summary', wagtail.fields.StreamField([('markdown', 0), ('paragraph', 1)], blank=True, block_lookup={0: ('core.blocks.MarkdownBlock', (), {}), 1: ('core.blocks.ParagraphBlock', (), {})})),
                ('related_datasets', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='related_articles', to='datasets.dataset')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
    ]
