# Generated by Django 6.0.8 on 2026-09-01 22:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('core', '0003_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basepage',),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='summary',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
