# Generated by Django 6.0.8 on 2026-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlepage_related_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
