# Generated by Django 6.0.8 on 2026-09-04 15:42

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('body', wagtail.fields.StreamField([('markdown', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('core.blocks.MarkdownBlock', (), {}), 1: ('core.blocks.ParagraphBlock', (), {}), 2: ('core.blocks.NarrativeImageBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('core.basepage',),
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
            ],
            options={
                'verbose_name': 'Privacy Page',
            },
            bases=('core.basepage',),
        ),
    ]
