# Generated by Django 6.0.8 on 2026-09-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact page', 'verbose_name_plural': 'Contact pages'},
        ),
        migrations.AlterModelOptions(
            name='privacypage',
            options={'verbose_name': 'Privacy page', 'verbose_name_plural': 'Privacy pages'},
        ),
    ]
