# Generated by Django 6.0.8 on 2026-08-29 15:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('core.blocks.ParagraphBlock', (), {}), 1: ('core.blocks.NarrativeImageBlock', (), {})}),
        ),
    ]
