# Generated by Django 6.0.8 on 2026-09-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basepage')),
            ],
            options={
                'verbose_name': 'Privacy Page',
            },
            bases=('core.basepage',),
        ),
    ]
