# Generated by Django 6.0.8 on 2026-09-03 16:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_intro_to_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='body',
            field=wagtail.fields.StreamField([('markdown', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('core.blocks.MarkdownBlock', (), {}), 1: ('core.blocks.ParagraphBlock', (), {}), 2: ('core.blocks.NarrativeImageBlock', (), {})}),
        ),
    ]
