# Generated by Django 6.0.8 on 2026-09-01 16:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('core.blocks.ParagraphBlock', (), {}), 1: ('core.blocks.NarrativeImageBlock', (), {})}),
        ),
    ]
